package codegen

// This code generated by go generate.
// DO NOT EDIT BY HAND!

type {{(Title .Name)}} struct {
{{range $jsonName, $val := .Fields}}
    {{- (Title $jsonName)}} {{(TypeOf $val)}} `json:"{{$jsonName}}"`
{{ end }}
}
