package codegen

// This code generated by go generate.
// DO NOT EDIT BY HAND!

type User struct {
	Bio             string `json:"bio"`
	Full_name       string `json:"full_name"`
	Id              string `json:"id"`
	Is_business     bool   `json:"is_business"`
	Profile_picture string `json:"profile_picture"`
	Username        string `json:"username"`
	Website         string `json:"website"`
}
